_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "<see instructions>"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

  MASK_ON: True
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "SyncBN"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 1
    NUM_CONV: 4
    POOLER_RESOLUTION: 7
    NORM: "SyncBN"
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    NORM: "SyncBN"

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896)
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 5000
  PRECISE_BN:
    ENABLED: True

SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  GAMMA: 0.25
  BASE_LR: 0.00025
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    ENABLED: False
    CLIP_TYPE: "value"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0

  # compared to standard detectron2, we add these two new configurations:
  OPTIMIZER: "ADAMW"
  LR_DECAY: 0.6
